before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=1
  id: wiregarden
  main: ./main.go
  binary: wiregarden
  goos:
  - linux
  goarch:
  - amd64
archives:
- format: binary
nfpms:
- package_name: wiregarden
  vendor: Wiregarden
  homepage: https://wiregarden.io/
  maintainer: Wiregarden Ops <ops@wiregarden.io>
  description: Grow your own private networks.
  license: BSL 1.1
  formats:
  - deb
  dependencies:
  - wireguard-tools
  bindir: /usr/bin
release:
  extra_files:
  - glob: ./install.bash
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
