name: ci

on:
  push:
    branches: [ master ]

jobs:
  unstable-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # need tags to calculate version
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    # Build and run tests
    - run: |
        go get -v -t -d ./...
    - run: go test -v ./...
    - run: go build -v -ldflags="-extldflags=-static" -tags netgo,usergo,sqlite_omit_load_extension .
    - run: cp $GOPATH/bin/wiregarden ./wiregarden

    # Store binary as build artifact
    - uses: actions/upload-artifact@v2
      with:
        name: wiregarden_linux_amd64
        path: ./wiregarden
