name: ci

on:
  push:
    branches: [ master ]

jobs:
  unstable-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # need tags to calculate version
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    # Build and run tests
    - run: |-
        echo "##[set-output name=version;]$(./scripts/version-next.bash || echo 0.0.0)"
        echo "##[set-output name=now;]$(date +%s)"
        echo "##[set-output name=commit;]$(git rev-parse --short HEAD)"
      id: getver
    - run: |
        go get -v -t -d ./...
    - run: go test -v ./...
    - run: go build -v -ldflags="-extldflags=-static -X github.com/wiregarden-io/wiregarden/cli.version=${{steps.getver.outputs.version}}~${{steps.getver.outputs.now}}-${{steps.getver.outputs.commit}}" -tags netgo,usergo,sqlite_omit_load_extension .
    - run: sha256sum ./wiregarden > SHA256SUMS

    # Store binary as build artifact
    - uses: actions/upload-artifact@v2
      with:
        name: wiregarden_linux_amd64
        path: ./wiregarden
    - uses: actions/upload-artifact@v2
      with:
        name: SHA256SUMS
        path: ./SHA256SUMS
